stages:
  - lint

eslint:
  image: node:latest
  stage: lint
  script:
    - npm install -g eslint eslint-config-wikimedia
    - eslint --init
    - eslint js --ignore-pattern 'lib/'
  cache:
    paths:
      - node_modules/

phpcs:
  image: php:7.1
  stage: lint
  script:
    - php composer.phar test
  cache:
    paths:
      - vendor/
      - composer.phar

  before_script:
    - apt-get update -yqq
    - apt-get install git -yqq
    #- docker-php-ext-install mbstring mcrypt pdo_pgsql curl json intl gd xml zip bz2 opcache
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

